- type: antag
  id: InitialInfected
  name: roles-antag-initial-infected-name
  antagonist: true
  setPreference: true
  objective: roles-antag-initial-infected-objective
  guides: [ Zombies ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h
# Harmony Change Start, IPCs can't be infected so can't be II
  - !type:SpeciesRequirement
    inverted: true
    species:
    - IPC
# Harmony Change End

- type: antag
  id: Zombie
  name: roles-antag-zombie-name
  antagonist: true
  setPreference: false
  objective: roles-antag-zombie-objective
# Harmony Change Start, IPCs can't be infected so can't be zombies (See if this can be changed?)
  requirements:
  - !type:SpeciesRequirement
    inverted: true
    species:
    - IPC
# Harmony Change End
  guides: [ Zombies ]
